### ISSUE TITLE
CPU LOAD IS VERY HIGH

### ISSUE THREAD

**Issue by thinkerthinker** [rmokady/mbu-content-tansfer#1]
hello, thank you for your excellent work.
when I run your code on my server, it takes so much CPU memory. it is strange. do you have any idea about this question?
hope for your reply!
![image](https://user-images.githubusercontent.com/37209045/65405344-4cbeec80-de0e-11e9-819a-bdf556b11285.png)

**Comment by rmokady** [comment]
Hi,
I do manage to run this code 8 times in parallel with a single CPU, so I don't suffer from too much CPU memory.
But, I did notice that Pytorch loaders by default create many threads that might make it hard for the CPU. So in this case I would try to force a limit on the created threads or set pin_memory=False, you can check https://github.com/pytorch/pytorch/issues/24809 .
