### ISSUE TITLE
downloader error

### ISSUE THREAD

**Issue by cymqqqq** [rmokady/mbu-content-tansfer#2]
downloader file : url of Dropbox not found 404

**Comment by rmokady** [comment]
celeba_downloader.sh may be broken

Can you try this [script](https://gist.github.com/charlesreid1/4f3d676b33b95fce83af08e4ec261822)?

**Comment by rmokady** [comment]
@cymqqqq

**Comment by cymqqqq** [comment]
thx
I got the dataset through the Google Drive
