### ISSUE TITLE
How to remove attributes?

### ISSUE THREAD

**Issue by kenoharada** [rmokady/mbu-content-tansfer#3]
First of all, Thank you for sharing awesome work!

I would like to test attribute removal of facial hair(such as Figure 6 and Figure 27 in your paper)

Could you tell me how to do that in your code??

And hyperparameter is showed in this?
>Hyperparameters for men hair segmentation ("dark hair to bald content transfer", use the bald condig in preprocess.py):

**Comment by rmokady** [comment]
Hi @kenoharada,
Thanks for your interest in our paper.
I just upload the code for removal and a pretrained model for facial hair.

**Comment by kenoharada** [comment]
Thank you very much for quick response and sharing code and the pretrained model!

**Comment by Rashid0125** [comment]
Your pretrained model link in not valid. Please provide the valid link.
