### ISSUE TITLE
Could you share more about the training settings?

### ISSUE THREAD

**Issue by zzxzzx123** [rmokady/mbu-content-tansfer#5]
Great work! Thanks for sharing your code. Could you share more about your training settings? (like the version and the number of GPUs you use, how long for training)

**Comment by rmokady** [comment]
I used one standard GPU, sometimes 1080 and sometimes Titan, I don't remember CUDA versions that I used.
I think it takes approximately around 12-24 hours to get good results.

**Comment by zzxzzx123** [comment]
Thank you.

**Comment by zzxzzx123** [comment]
> I used one standard GPU, sometimes 1080 and sometimes Titan, I don't remember CUDA versions that I used.
> I think it takes approximately around 12-24 hours to get good results.

Thank you.
