### ISSUE TITLE
Parameter tuning

### ISSUE THREAD

**Issue by tkuanlun350** [rmokady/mbu-content-tansfer#6]
Hi ! 

Thanks for your great work and detailed documentation.

I am noticing that you used different parameter for different task and I am wondering if you can you also give me some insight of how to tune the parameter for different task ?

Thank you !

**Comment by rmokady** [comment]
Hi, 
For fast results I would start with something like
--alpha1 0.5 --alpha2 0.5 --beta1 0.0 --beta2 0.0001 --gama 5.0 --delta 5.0

Then I would change the alpha according to the size of the obtained mask
And finally try different values for beta2

If you have the resources you can try a more exhaustive search

**Comment by tkuanlun350** [comment]
Thanks for the reply ! 

Just to clarify, I thought reconstruct loss 2 (delta an gamma) should be the one to encourage small mask size ?

For my glasses dataset, I observed that the mask area is too large (expand to nose and jaw region), I am wondering if manual post-processing would help ? like mask out the area based on the facial landmark.
